### ISSUE TITLE
Нужно брать продукты из поля объекта (а не из параметра)

### ISSUE THREAD

**Issue by coursar** [ElenaVeselovskaya/ulmart#2]
https://github.com/ElenaVeselovskaya/ulmart/blob/3ebd9ac4d22c7678925d0010d472c95e87e7e33c/src/main/java/ru/itpark/service/UlmartService.java#L47-L62

**Comment by ElenaVeselovskaya** [comment]
пофиксила

**Comment by coursar** [comment]
Так надо коммитом закрывать, а не руками
